# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d79c6d660c54511b27b739aaa874b2c0310da1665bcccce7f2421a90035050311cbe40940b5cbc40c6a086023a48e20f1e2f85d6400cab5b3b83560e1241f15c

test:
  secret_key_base: 020173a30192cd8410c301dc956e231719ccf69c8822cd5597fb4776dba946fd486f88234cc9ab1e57b427fd03e98a44412da803dc122a00ffa00c6d6065da58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
